# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('donation_items', jsonfield.fields.JSONField()),
            ],
        ),
    ]
