# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('contact_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='DonationModel',
        ),
    ]
