# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0002_auto_20170812_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_address', models.TextField()),
                ('donation_items', jsonfield.fields.JSONField()),
                ('receiver_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor', to='donationApp.UserModel')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='donationApp.UserModel')),
            ],
        ),
    ]
