# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationApp', '0004_auto_20170830_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='donor_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donationmodel',
            name='receiver_email',
            field=models.EmailField(max_length=254),
        ),
    ]
